version: '3.8'
services:
    europaserver:
        image: europaserver
        container_name: europaserver
        tty: true
        stdin_open: true
        restart: always
    europaclient:
        image: europaclient
        container_name: europaclient
        ports:
            - 80:8080
        depends_on:
            - europadb
    europadb:
        image: mysql:5.6
        container_name: europadb
        environment:
            MYSQL_DATABASE: 'europa'
            MYSQL_USER: 'europa'
            MYSQL_PASSWORD: 'silverlining'
            MYSQL_ROOT_PASSWORD: 'threeblindmice'
        volumes:
            - ./mysql/init.sql:docker-entrypoint-initdb.d
            - /opt/apps/europadb:/var/lib/mysql
        #ports:
        #    - 3306:3306
