version: '3.8'
services:
    archangeldb:
        image: archangeldb
        container_name: archangeldb
        tty: true
        stdin_open: true
        restart: always
    service:
        image: archangelms
        container_name: archangelms
        ports:
            - 8880:8080
        depends_on:
            - archangeldb
    ui:
        image: archangelui
        container_name: archangelui
        ports:
            - 80:8080
        depends_on:
            - service

    dozzle:
        image: amir20/dozzle
        container_name: dozzle
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
